import { useState } from "react";
import { Modal, Button } from "../../../../src/index";

export default function ModalPage() {
  const [openSize, setOpenSize] = useState(null);

  return (
    <section className="content-section">
      <div className="page-header">
        <h1 className="section-title">Modal</h1>
        <p className="lead">
          A focus-trapping dialog rendered over the page. Generated by RPS Studio from the Figma
          definition.
        </p>
      </div>

      <section className="section">
        <h2 className="section-subtitle">Sizes</h2>
        <div className="demo-box">
          {["Small", "Medium", "Large", "xx-Large"].map((size) => (
            <Button key={size} variant="outline" onClick={() => setOpenSize(size)}>
              Open {size.toLowerCase()}
            </Button>
          ))}
        </div>

        <Modal open={openSize !== null} onClose={() => setOpenSize(null)} size={openSize ?? "Medium"}>
          <h2 className="section-heading">{openSize} modal</h2>
          <p>
            Focus is trapped inside the dialog while it is open, and Escape closes it. Both are
            behaviours of the component, not of this page.
          </p>
          <Button onClick={() => setOpenSize(null)}>Close</Button>
        </Modal>
      </section>

      <section className="section">
        <h2 className="section-subtitle">Props</h2>
        <table className="props-table">
          <thead>
            <tr>
              <th>Prop</th>
              <th>Values</th>
              <th>Required</th>
            </tr>
          </thead>
          <tbody>
            <tr><td><code>open</code></td><td><code>true false</code></td><td>yes</td></tr>
            <tr><td><code>onClose</code></td><td><code>() =&gt; void</code></td><td>yes</td></tr>
            <tr><td><code>size</code></td><td><code>Small Medium Large xx-Large</code></td><td>no</td></tr>
            <tr><td><code>children</code></td><td><code>ReactNode</code></td><td>yes</td></tr>
          </tbody>
        </table>
      </section>
    </section>
  );
}
