import { Link } from "react-router-dom";
import { components } from "../components/Sidebar";

/**
 * The front door. Counts come from the same discovered registry the sidebar uses, so the number on
 * this page and the number in the nav cannot disagree.
 */
export default function Overview() {
  const generated = components.filter((c) => c.generated);
  const handwritten = components.filter((c) => !c.generated);

  return (
    <section className="content-section">
      <div className="page-header home-hero">
        <h1 className="section-title">Oranje Design System</h1>
        <p className="lead">
          A small React design system: design tokens as CSS custom properties, and components that
          reference them by name. Maintained with RPS Studio — Figma and code are audited against
          one another, and the gaps are closed by pull request.
        </p>
      </div>

      <div className="stat-grid">
        <div className="stat-card">
          <span className="stat-value">{components.length}</span>
          <span className="stat-label">Components</span>
        </div>
        <div className="stat-card">
          <span className="stat-value">{generated.length}</span>
          <span className="stat-label">Generated by RPS</span>
        </div>
        <div className="stat-card">
          <span className="stat-value">{handwritten.length}</span>
          <span className="stat-label">Written by hand</span>
        </div>
      </div>

      <section className="section">
        <h2 className="section-subtitle">What has been generated</h2>
        <p>
          Components written into <code>src/components/figma</code> arrived through an RPS Studio
          pull request, raised against a coverage gap the audit found between the Figma library and
          this repository. They are flagged <strong>RPS</strong> in the sidebar.
        </p>
        {generated.length > 0 ? (
          <ul>
            {generated.map((c) => (
              <li key={c.path}>
                <Link to={c.path}>{c.label}</Link>
              </li>
            ))}
          </ul>
        ) : (
          <p>Nothing generated yet — every component here was written by hand.</p>
        )}
      </section>

      <section className="section">
        <h2 className="section-subtitle">Installation</h2>
        <pre>
          <code>{`npm install
npm run dev --workspace oranje-docs`}</code>
        </pre>
        <p>
          Import a component from the package entry point. Every component is exported from{" "}
          <code>src/index.ts</code>; one that is not exported is unreachable, which is why the
          pipeline updates the barrel in the same pull request as the component.
        </p>
        <pre>
          <code>{`import { Button } from "oranje-ds";

<Button variant="primary" size="md">Save changes</Button>`}</code>
        </pre>
      </section>

      <section className="section">
        <h2 className="section-subtitle">Tokens</h2>
        <p>
          All colour, radius, spacing and type values live in{" "}
          <code>src/styles/tokens.css</code>. Components reference them as{" "}
          <code>var(--color-primary)</code> and never inline a literal, so a palette change is a
          one-file edit. This documentation site imports the same file, so the page and the
          components can never drift apart.
        </p>
      </section>
    </section>
  );
}
