import { useState } from "react";
import { Pill } from "../../../../src/index";

const VARIANTS = ["default", "destructive"];
const SIZES = ["small", "medium", "large"];

export default function PillPage() {
  const [clicks, setClicks] = useState(0);

  return (
    <section className="content-section">
      <div className="page-header">
        <h1 className="section-title">Pill</h1>
        <p className="lead">
          A compact, optionally interactive label. Generated by RPS Studio from the Figma
          definition.
        </p>
      </div>

      <section className="section">
        <h2 className="section-subtitle">Variants</h2>
        <div className="demo-box">
          {VARIANTS.map((variant) => (
            <Pill key={variant} variant={variant}>
              {variant}
            </Pill>
          ))}
        </div>
      </section>

      <section className="section">
        <h2 className="section-subtitle">Sizes</h2>
        <div className="demo-box">
          {SIZES.map((size) => (
            <Pill key={size} size={size}>
              {size}
            </Pill>
          ))}
        </div>
      </section>

      <section className="section">
        <h2 className="section-subtitle">Interactive</h2>
        <div className="demo-box">
          <Pill onClick={() => setClicks((n) => n + 1)}>Clicked {clicks}×</Pill>
          <Pill onClick={() => setClicks((n) => n + 1)} disabled>
            Disabled
          </Pill>
          <Pill variant="destructive" onClick={() => setClicks(0)}>
            Reset
          </Pill>
        </div>
        <p>
          A pill with an <code>onClick</code> is keyboard operable — Enter and Space activate it, and
          a disabled pill ignores both.
        </p>
      </section>

      <section className="section">
        <h2 className="section-subtitle">Props</h2>
        <table className="props-table">
          <thead>
            <tr>
              <th>Prop</th>
              <th>Values</th>
              <th>Default</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>children</code></td>
              <td><code>ReactNode</code></td>
              <td>—</td>
            </tr>
            <tr>
              <td><code>variant</code></td>
              <td><code>default destructive</code></td>
              <td><code>default</code></td>
            </tr>
            <tr>
              <td><code>size</code></td>
              <td><code>small medium large</code></td>
              <td><code>medium</code></td>
            </tr>
            <tr>
              <td><code>onClick</code></td>
              <td><code>() =&gt; void</code></td>
              <td>—</td>
            </tr>
            <tr>
              <td><code>disabled</code></td>
              <td><code>true false</code></td>
              <td><code>false</code></td>
            </tr>
          </tbody>
        </table>
      </section>
    </section>
  );
}
