import { Tags } from "../../../../src/index";

const STATES = ["Default", "Hover", "Focussed", "Pressed", "Disabled"];

export default function TagsPage() {
  return (
    <section className="content-section">
      <div className="page-header">
        <h1 className="section-title">Tags</h1>
        <p className="lead">
          Labels items that need to be categorised or organised by keyword. Generated by RPS Studio
          from the Figma definition.
        </p>
      </div>

      <section className="section">
        <h2 className="section-subtitle">States</h2>
        <div className="demo-box">
          {STATES.map((state) => (
            <Tags key={state} size="Medium" state={state} selected={false} style="Rounded">
              {state}
            </Tags>
          ))}
        </div>
        <p>
          The state axis is spelled <code>Focussed</code> — carried over verbatim from the Figma
          library, where the same typo appears. The audit flags it rather than the generator
          silently correcting it, because renaming a variant is a design-system decision.
        </p>
      </section>

      <section className="section">
        <h2 className="section-subtitle">Selected</h2>
        <div className="demo-box">
          <Tags size="Medium" state="Default" selected={false} style="Rounded">
            Unselected
          </Tags>
          <Tags size="Medium" state="Default" selected style="Rounded">
            Selected
          </Tags>
        </div>
      </section>

      <section className="section">
        <h2 className="section-subtitle">Size and shape</h2>
        <div className="demo-box">
          <Tags size="Small" state="Default" selected={false} style="Rounded">
            Small rounded
          </Tags>
          <Tags size="Medium" state="Default" selected={false} style="Rounded">
            Medium rounded
          </Tags>
          <Tags size="Small" state="Default" selected={false} style="Rectangle">
            Small rectangle
          </Tags>
          <Tags size="Medium" state="Default" selected={false} style="Rectangle">
            Medium rectangle
          </Tags>
        </div>
      </section>

      <section className="section">
        <h2 className="section-subtitle">Props</h2>
        <table className="props-table">
          <thead>
            <tr>
              <th>Prop</th>
              <th>Values</th>
              <th>Required</th>
            </tr>
          </thead>
          <tbody>
            <tr><td><code>size</code></td><td><code>Medium Small</code></td><td>yes</td></tr>
            <tr>
              <td><code>state</code></td>
              <td><code>Default Disabled Focussed Hover Pressed</code></td>
              <td>yes</td>
            </tr>
            <tr><td><code>selected</code></td><td><code>true false</code></td><td>yes</td></tr>
            <tr><td><code>style</code></td><td><code>Rectangle Rounded</code></td><td>yes</td></tr>
          </tbody>
        </table>
      </section>
    </section>
  );
}
